# Generated by Django 3.1.2 on 2021-07-25 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20210724_1401'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='apartment',
            field=models.CharField(blank=True, default='', max_length=15, verbose_name='Apartment'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='building',
            field=models.CharField(blank=True, default='', max_length=15, verbose_name='Building'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='street',
            field=models.CharField(default='', max_length=100, verbose_name='Street'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='structure',
            field=models.CharField(blank=True, default='', max_length=15, verbose_name='Structure'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='telegram',
            field=models.CharField(blank=True, default='', max_length=150, verbose_name='Telegram'),
        ),
    ]
