# Generated by Django 3.1.2 on 2021-07-27 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20210726_1153'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='chat_bot_id',
            field=models.TextField(null=True, verbose_name='chat_bot_id'),
        ),
    ]
