# Generated by Django 3.1.2 on 2021-07-26 12:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_auto_20210725_1947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderworker',
            name='order_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='orders.order'),
        ),
    ]
