# Generated by Django 3.1.2 on 2021-07-29 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_auto_20210726_1624'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_type',
            field=models.CharField(choices=[('R', 'Repair'), ('M', 'Maintenance'), ('C', 'Consultation')], default='C', max_length=1),
        ),
    ]
